apiVersion: v1
kind: Template
metadata:
  name: minishift-chrony
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: minishift-chrony
    name: minishift-chrony
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: minishift-chrony
    name: minishift-chrony
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: minishift-chrony:latest
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/aclarkrh/minishift-chrony.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: rhel:latest
          namespace: openshift
      type: Docker
    triggers: []
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: minishift-chrony
    name: minishift-chrony
  spec:
    replicas: 1
    selector:
      app: minishift-chrony
      deploymentconfig: minishift-chrony
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: minishift-chrony
          deploymentconfig: minishift-chrony
      spec:
        containers:
        - image: minishift-chrony:latest
          imagePullPolicy: Always
          name: minishift-chrony
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        serviceAccount: minishift-chrony
        serviceAccountName: minishift-chrony
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - minishift-chrony
        from:
          kind: ImageStreamTag
          name: minishift-chrony:latest
      type: ImageChange
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app: minishift-chrony
    name: minishift-chrony